- type: job
  id: AdministrativeAssistant
  name: job-name-admin-assistant
  description: job-description-admin-assistant
  playTimeTracker: JobAdminAssistant
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Engineering
      min: 7200 # 2 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Logistics
      min: 7200 # 2 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Medical
      min: 7200 # 2 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Civilian
      min: 7200 # 2 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 7200 # 2 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Epistemics
      min: 7200 # 2 hours
    - !type:CharacterTraitRequirement
      inverted: true
      traits:
        - Foreigner
        - ForeignerLight
  startingGear: AdminAssistantGear
  icon: "JobIconAdminAssitant"
  supervisors: job-supervisors-command
  canBeAntag: false
  access:
    - Command
    - Maintenance
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]
    - !type:AddComponentSpecial
      components:
      - type: CommandStaff

- type: startingGear
  id: AdminAssistantGear
  subGear:
  - AdminAssistantPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAdminAssistant
    id: AdminAssistantPDA
    ears: ClothingHeadsetAdminAssist
    shoes: ClothingShoesLeather
  innerClothingSkirt: ClothingUniformJumpskirtAdminAssistant

- type: startingGear
  id: AdminAssistantPlasmamanGear
  parent: BasePlasmamanGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitAdminAssistant
    head: ClothingHeadEnvirohelmAdminAssistant
    gloves: ClothingHandsGlovesEnviroglovesAdminAssistant
